default:
  image: quay.io/element84/e84-build-filmdrop:1.5.7-main

.common_variables:
  variables:
    STAC_SERVER_TAG_DEV: v2.2.3
    STAC_SERVER_TAG_RELEASE: v2.2.3

.setup_and_validate:
  script:
    - export CI=true
    - export FILMDROP_BUILD_DIR=`pwd`
    - export STAC_SERVER_DIR="stac-server-${STAC_SERVER_TAG:1}"
    - . $HOME/.nvm/nvm.sh
    - nvm use v16
    - echo "Building stac-server..."
    - curl -L -f --no-progress-meter -o stac-server.tgz "https://github.com/stac-utils/stac-server/archive/refs/tags/${STAC_SERVER_TAG}.tar.gz"
    - tar -xzf stac-server.tgz
    - cd "$STAC_SERVER_DIR"
    - npm install
    - BUILD_PRE_HOOK=true npm run build
    - mkdir -p $FILMDROP_BUILD_DIR/modules/stac-server/lambda/api
    - cp dist/api/api.zip $FILMDROP_BUILD_DIR/modules/stac-server/lambda/api/
    - mkdir -p $FILMDROP_BUILD_DIR/modules/stac-server/lambda/ingest
    - cp dist/ingest/ingest.zip $FILMDROP_BUILD_DIR/modules/stac-server/lambda/ingest/
    - mkdir -p $FILMDROP_BUILD_DIR/modules/stac-server/lambda/pre-hook
    - cp dist/pre-hook/pre-hook.zip $FILMDROP_BUILD_DIR/modules/stac-server/lambda/pre-hook/
    - cd $FILMDROP_BUILD_DIR/modules
    # - pre-commit run --all-files

dev_validate:
  extends: [.common_variables]
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
  variables:
    STAC_SERVER_TAG: ${STAC_SERVER_TAG_DEV}
  script:
    - !reference [.setup_and_validate, script]

version_validate:
  extends: [.common_variables]
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(\d+.)(\d+.)(\d+)(-[.\d\w]+)?$/
      when: on_success
  variables:
    STAC_SERVER_TAG: ${STAC_SERVER_TAG_RELEASE}
  script:
    - !reference [.setup_and_validate, script]
