version: 0.2

phases:
  build:
    commands:
      - echo "Pulling FilmDrop UI Console release ..."
      - wget --secure-protocol=TLSv1_2 -q -O filmdrop-ui.tgz "https://github.com/Element84/filmdrop-ui/archive/refs/tags/${FILMDROP_UI_TAG}.tar.gz"
      - export CONSOLE_UI_DIR="filmdrop-ui-${FILMDROP_UI_TAG:1}"
      - tar -xzf filmdrop-ui.tgz
      - cd "$CONSOLE_UI_DIR"
      - rm -f ./src/assets/config.*
      - echo "Setting environment variables for the Console UI ..."
      - echo $FILMDROP_UI_CONFIG | base64 --decode >> ./public/config/config.json
      - echo $FILMDROP_UI_LOGO | base64 --decode >> ./public/${FILMDROP_UI_LOGO_FILE##*/}
      - echo "Building FilmDrop UI Console release ..."
      - npm install
      - npm run build
      - cd build
      - echo "Pushing FilmDrop UI Console release to S3..."
      - aws s3 sync --delete . s3://$CONTENT_BUCKET --acl bucket-owner-full-control
