name: 🚀 Deploy Development

on:
  push:
    branches:
      - main
    tags:
      - v.*

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy-wf.yaml
    secrets: inherit
    concurrency: staging
    with:
      stage: staging
      url: https://console.dev.example.com
      fd-aws-tf-modules-version: v2.24.0
