name: Continuous integration

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

jobs:
  update-lambdas:
    runs-on: ubuntu-latest
    env:
      CI: true
      STAC_SERVER_TAG: v3.5.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.3"

      - name: Update stac-server lambdas
        id: update_stac_lambdas
        run: ./scripts/update-lambdas.sh

      - name: Terraform Init
        id: tf_init
        run: terraform init

      - name: Terraform Validate
        id: tf_validate
        run: terraform validate -no-color
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.3"
      - uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: "v0.49.0"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11" 
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files